/** A curated set of concise, open-ended behavioral interview prompts. */
export const behavioralQuestions = [
  "Tell me about a time you turned a difficult situation into a positive outcome.",
  "Describe a project you took from an early idea to a finished result.",
  "Tell me about a time you had to learn a new skill quickly to get something done.",
  "Describe a time you received feedback that changed how you work.",
  "Tell me about a time you disagreed with a teammate and how you handled it.",
  "Share an example of a mistake you made and what you learned from it.",
  "Describe a time you had to deliver important work under a tight deadline.",
  "Tell me about a time you used data or evidence to make a decision.",
  "Describe a time you had to explain a complex idea to someone new to it.",
  "Tell me about a time you made a process simpler or more efficient.",
  "Share an example of when you took ownership beyond your usual responsibilities.",
  "Describe a time you had to adapt when a project changed direction.",
  "Tell me about a time you helped resolve tension within a team.",
  "Describe a decision you made with incomplete information.",
  "Tell me about a time you missed a goal and how you responded.",
  "Share a time you persuaded others to support an idea or change.",
  "Describe a time you balanced several competing priorities.",
  "Tell me about a time you spotted a risk before it became a problem.",
  "Describe a time you built trust with a colleague, customer, or partner.",
  "Tell me about a time you had to deliver difficult news with care.",
  "Share an example of when you made a customer or user feel heard.",
  "Describe a time you worked with someone whose style differed from yours.",
  "Tell me about a time you had to make progress with limited resources.",
  "Describe a time you challenged an assumption and what happened next.",
  "Tell me about a time you improved a product or experience using user feedback.",
  "Share a time you had to protect quality while moving quickly.",
  "Describe a time you contributed to an inclusive and welcoming team.",
  "Tell me about a time you used a new tool or technology to solve a problem.",
  "Describe a time you had to make a responsible decision about AI or automation.",
  "Tell me about a time you influenced a team without being the decision-maker.",
  "Share an example of a goal you set and how you stayed accountable to it.",
  "Describe a time you changed your mind after hearing another perspective.",
  "Tell me about a time you had to work through ambiguity.",
  "Describe a time you helped a teammate grow or succeed.",
  "Tell me about a time you found a creative solution to a recurring problem.",
  "Share a time you had to choose between speed, cost, and quality.",
  "Describe a time you communicated across different teams or time zones.",
  "Tell me about a time a plan failed and how you recovered.",
  "Describe a time you used a small experiment to test a big idea.",
  "Tell me about a time you advocated for a user or customer who was overlooked.",
  "Share an example of how you handled a sudden change in priorities.",
  "Describe a time you made a difficult trade-off and explained your reasoning.",
  "Tell me about a time you noticed a gap and took initiative to fill it.",
  "Describe a time you helped a group reach alignment on a tough decision.",
  "Tell me about a time you had to rebuild confidence after a setback.",
  "Share a time you used clear communication to prevent confusion or rework.",
  "Describe a time you protected sensitive information or earned someone's trust.",
  "Tell me about a time you delivered a result you are especially proud of.",
  "Describe a time you had to stop or rethink work that was no longer valuable.",
  "Tell me about a time you made a positive impact beyond your own team.",
  "Share a time you faced an unfamiliar challenge and found your way forward.",
] as const;
