import { allCategoryPrompts } from "./topicBank";

/** Local definitions for every prompt. Keeping this map in the app means hints work offline. */
const definitions: Record<string, string> = {
  "a tiny act of courage": "A small action that takes bravery despite uncertainty or fear.",
  curiosity: "A strong desire to know, learn, or understand something.",
  courage: "The ability to face fear, danger, or difficulty with confidence.",
  empathy: "The ability to understand and share another person’s feelings.",
  patience: "The ability to wait or endure difficulty without becoming upset.",
  resilience: "The ability to recover and adapt after difficulty or change.",
  gratitude: "The quality of feeling and expressing appreciation for what one has.",
  honesty: "The quality of being truthful and sincere.",
  trust: "A firm belief in someone’s reliability, truth, or ability.",
  kindness: "The quality of being considerate, generous, and helpful to others.",
  ambition: "A strong desire to achieve a particular goal or level of success.",
  balance: "A stable or fair relationship between different needs or influences.",
  change: "The act or result of becoming different.",
  failure: "A lack of success in achieving an intended result.",
  success: "The achievement of an aim or a desired result.",
  freedom: "The state of being able to act or choose without undue restraint.",
  identity: "The qualities and experiences that make a person or group distinct.",
  belonging: "The feeling of being accepted as part of a group or place.",
  friendship: "A close relationship of mutual affection, trust, and support.",
  leadership: "The ability to guide, influence, or direct a group of people.",
  responsibility: "A duty to deal with something or to answer for one’s actions.",
  confidence: "A feeling of trust in one’s abilities, judgment, or qualities.",
  uncertainty: "The state of not knowing or being unable to predict something.",
  creativity: "The ability to produce original ideas or make imaginative things.",
  discipline: "The practice of training oneself to follow rules or reach a goal.",
  perspective: "A particular way of viewing or understanding a situation.",
  communication: "The exchange of information, ideas, or feelings between people.",
  opportunity: "A favorable situation that makes it possible to do something.",
  tradition: "A custom or belief passed from one generation to another.",
  community: "A group of people connected by place, interests, or shared identity.",
  wonder: "A feeling of surprise and admiration caused by something remarkable.",
  budgeting: "The process of planning how income will be spent and saved.",
  saving: "The act of setting money aside instead of spending it.",
  investing: "Putting money into assets with the aim of earning a future return.",
  compounding: "The growth of money as returns earn further returns over time.",
  inflation: "A general rise in prices that reduces the purchasing power of money.",
  debt: "Money that is owed to another person or organization.",
  credit: "An agreement allowing someone to borrow money and repay it later.",
  equity: "The value of an ownership share after debts are subtracted.",
  liquidity: "How easily an asset can be turned into cash without losing value.",
  diversification: "Spreading investments across assets to reduce exposure to one risk.",
  mortgage: "A loan used to buy property and secured against that property.",
  insurance: "Protection against financial loss in exchange for regular payments.",
  taxation: "The system of collecting compulsory payments to fund public services.",
  retirement: "The period of life after a person stops working permanently.",
  pension: "Regular income paid to someone after retirement.",
  annuity: "A financial product that pays a series of income payments over time.",
  portfolio: "A collection of investments held by a person or organization.",
  dividend: "A portion of company profits paid to its shareholders.",
  interest: "The cost of borrowing money or the return earned on savings.",
  principal: "The original amount of money borrowed or invested.",
  yield: "The income an investment produces, usually expressed as a percentage.",
  risk: "The possibility that an outcome will differ from what is expected.",
  frugality: "The careful use of money and resources to avoid waste.",
  cashflow: "The movement of money into and out of a person or organization.",
  affordability: "The ability to pay for something without undue financial strain.",
  solvency: "The ability to meet financial obligations as they become due.",
  leverage: "The use of borrowed money or resources to increase potential returns.",
  wealth: "An abundance of valuable possessions, assets, or resources.",
  scarcity: "A limited supply of something compared with the desire for it.",
  windfall: "An unexpected gain of money or other valuable benefit.",
  founder: "A person who establishes an organization or starts a company.",
  venture: "A project or business activity involving risk and possible reward.",
  bootstrapping: "Building a business using personal funds and its own early revenue.",
  validation: "Evidence that an idea or product solves a real customer need.",
  customer: "A person or organization that buys or uses a product or service.",
  market: "The group of buyers and sellers for a particular product or service.",
  product: "An item or service created to meet a need or provide value.",
  pricing: "The process of deciding how much a product or service will cost.",
  revenue: "Income a business earns from selling goods or services.",
  margin: "The difference between revenue and a related cost, often shown as a percentage.",
  distribution: "The process of delivering products or content to intended users.",
  positioning: "The way a brand or product is presented in relation to alternatives.",
  branding: "The process of creating a recognizable identity for a product or organization.",
  storytelling: "The art of communicating events or ideas through a narrative.",
  networking: "Building and maintaining professional or social relationships.",
  negotiation: "A discussion in which people seek agreement on different interests.",
  iteration: "A repeated version of a process or product, often improved each time.",
  traction: "Evidence that a business or product is gaining customer interest and use.",
  scale: "The size or extent of something, or the act of growing it efficiently.",
  delegation: "The assignment of responsibility or tasks to another person.",
  partnership: "A relationship in which people or organizations work toward shared aims.",
  ownership: "The state of possessing, controlling, or being responsible for something.",
  innovation: "The introduction of a new idea, method, or useful improvement.",
  strategy: "A plan designed to achieve a long-term aim.",
  execution: "The act of carrying out a plan or putting an idea into practice.",
  mentorship: "Guidance provided by a more experienced person to support someone’s growth.",
  adaptability: "The ability to adjust effectively to new conditions or circumstances.",
  mvp: "A first product version with enough features to test an idea with users.",
  prototype: "An early model made to test or demonstrate a product or idea.",
  pitch: "A short presentation intended to persuade someone to support an idea.",
  runway: "The time a startup can operate before its available cash runs out.",
  pivot: "A significant change in a company’s strategy, product, or business model.",
  accelerator: "A program that helps early companies grow through mentoring and resources.",
  incubator: "A program or space that supports the development of new businesses.",
  seed: "Early investment used to help a new business begin developing.",
  preseed: "Very early startup funding used to develop and validate an initial idea.",
  seriesa: "A startup’s first major venture-capital funding round after seed funding.",
  captable: "A record of who owns a company and how much of it each person owns.",
  dilution: "A reduction in an owner’s percentage of a company after new shares are issued.",
  burnrate: "The rate at which a company spends its available cash.",
  retention: "The ability to keep customers, users, or employees over time.",
  churn: "The rate at which customers stop using a service or cancel a subscription.",
  acquisition: "The process of gaining customers, users, or ownership of another company.",
  onboarding: "The process of helping a new user or employee get started.",
  cohort: "A group of people who share a starting point or experience.",
  activation: "The point when a new user first experiences a product’s key value.",
  scalability: "The ability to grow while handling greater demand or workload.",
  unicorn: "A privately held startup valued at one billion dollars or more.",
  growth: "An increase in size, number, value, or development over time.",
  disruption: "A major change that challenges established ways of doing business.",
  monetization: "The process of earning revenue from a product, service, or audience.",
  saas: "Software delivered over the internet, usually through a subscription.",
  fintech: "Technology used to provide or improve financial services.",
  roadmap: "A plan showing the intended direction and milestones of a project or product.",
  agents: "Software systems that can carry out tasks toward a goal with some independence.",
  inference: "The process of using a trained AI model to produce an output.",
  tokens: "Units of text that language models process and generate.",
  transformer: "A neural-network architecture that uses attention to process sequences of data.",
  embedding: "A numerical representation that places data in a space of related meanings.",
  multimodal: "Able to process or combine more than one kind of data, such as text and images.",
  robotics: "The design and use of machines that can perform physical tasks.",
  automation: "The use of technology to perform tasks with reduced human effort.",
  model: "A simplified representation or a trained system used to make predictions or generate output.",
  dataset: "A structured collection of information used for analysis or training.",
  benchmark: "A standard test used to compare performance or quality.",
  alignment: "The effort to make an AI system’s behavior match intended goals and values.",
  hallucination: "An AI-generated claim that sounds plausible but is false or unsupported.",
  prompt: "An instruction or input that guides a person or AI system’s response.",
  context: "The surrounding information that helps explain the meaning of something.",
  latency: "The delay between an action or request and its response.",
  compute: "The processing power and resources used to perform calculations.",
  silicon: "A chemical element widely used to make computer chips and electronic devices.",
  gpu: "A processor designed to handle many calculations in parallel, often for graphics or AI.",
  neural: "Relating to nerves, the brain, or systems modeled on them.",
  synthetic: "Made or produced artificially rather than occurring naturally.",
  deepfake: "Synthetic media altered or generated to make someone appear to say or do something.",
  privacy: "The right or ability to control access to personal information and life.",
  bias: "A preference or tendency that unfairly influences judgment or results.",
  opensource: "Software whose source code is available for people to inspect and modify.",
  edge: "A device or location near where data is produced, where processing can happen locally.",
  cloud: "Remote computing services delivered over the internet.",
  quantum: "Relating to the physical behavior of matter and energy at very small scales.",
  interface: "A point or system through which a person or device interacts with another.",
  algorithm: "A defined set of steps for solving a problem or completing a computation.",
  strength: "The ability of a person or object to exert force or withstand pressure.",
  endurance: "The ability to sustain physical or mental effort over time.",
  mobility: "The ability to move freely and easily.",
  cardio: "Exercise that raises the heart rate and improves heart and lung fitness.",
  hypertrophy: "An increase in the size of a muscle or other tissue.",
  recovery: "The process of returning to health or readiness after exertion or illness.",
  consistency: "The quality of acting or performing in a steady, reliable way.",
  progression: "Gradual movement toward a more advanced level or greater difficulty.",
  flexibility: "The ability of a joint or body to move through a range of motion.",
  posture: "The way a person holds or positions their body.",
  stamina: "The ability to continue physical or mental activity without tiring quickly.",
  agility: "The ability to move quickly and change direction with control.",
  coordination: "The ability to use different body parts or actions together smoothly.",
  resistance: "Opposition to a force, movement, change, or influence.",
  movement: "The act or process of changing position or moving the body.",
  warmup: "Light activity done before exercise to prepare the body for effort.",
  cooldown: "Gentle activity after exercise that helps the body return to rest.",
  training: "Practice or instruction that develops a skill, ability, or fitness.",
  sprint: "A short, fast run or burst of intense effort.",
  marathon: "A long-distance running race of 42.195 kilometers, or a very extended task.",
  cycling: "The activity or sport of riding a bicycle.",
  walking: "Moving at a regular pace on foot.",
  calisthenics: "Strength exercises that use body weight for resistance.",
  yoga: "A practice combining physical postures, breathing, and attention.",
  pilates: "A system of exercises focused on controlled movement and core strength.",
  protein: "A nutrient made of amino acids that helps build and repair body tissues.",
  sleep: "A recurring natural state of rest in which awareness is reduced.",
  heartrate: "The number of times a heart beats in one minute.",
  fiber: "The part of plant foods that the body cannot fully digest.",
  micronutrients: "Vitamins and minerals needed by the body in small amounts.",
  hydration: "The process or state of supplying the body with enough water.",
  fermentation: "The conversion of sugars by microorganisms, often used to preserve food.",
  probiotics: "Live microorganisms that can support a healthy balance of gut microbes.",
  microbiome: "The community of microorganisms living in a particular environment, such as the gut.",
  calories: "Units used to measure the energy supplied by food.",
  satiety: "The feeling of fullness that reduces the desire to eat.",
  metabolism: "The chemical processes by which the body uses energy and maintains itself.",
  glucose: "A simple sugar that is an important source of energy for the body.",
  electrolytes: "Minerals in body fluids that carry electrical charges and support key functions.",
  omega3: "A family of essential fats that support normal body functions.",
  antioxidants: "Substances that help limit cell damage caused by reactive molecules.",
  nutrients: "Substances in food that the body needs for energy, growth, and health.",
  wholefoods: "Foods that are minimally processed and close to their natural form.",
  legumes: "Plants such as beans, lentils, and peas, often rich in protein and fiber.",
  greens: "Green leafy vegetables eaten as food.",
  carbohydrates: "Sugars, starches, and fibers that are a major source of dietary energy.",
  fats: "Nutrients that store energy and help the body absorb certain vitamins.",
  minerals: "Naturally occurring elements the body needs for structure and normal function.",
  vitamins: "Organic nutrients required in small amounts for normal growth and body function.",
  sodium: "A mineral that helps regulate fluid balance and nerve and muscle function.",
  digestion: "The process of breaking food down so the body can absorb and use it.",
  prebiotic: "A substance, often a type of fiber, that feeds beneficial gut microbes.",
  supplements: "Products taken to add nutrients or other substances to the diet.",
  portions: "The amounts of food served or eaten at one time.",
  seasonality: "The way availability or activity changes with the seasons.",
  sustainability: "The ability to continue over time without exhausting resources or causing lasting harm.",
  ingredients: "The individual foods or substances used to make a dish or product.",
  focus: "The ability to direct attention toward a particular task or subject.",
  prioritization: "The act of deciding which tasks or needs are most important.",
  planning: "The process of deciding in advance how to achieve an aim.",
  batching: "Grouping similar tasks and completing them together.",
  deepwork: "Focused work done without distraction on a demanding task.",
  cadence: "A regular rhythm or pattern in which something happens.",
  momentum: "The force or progress that keeps an activity moving forward.",
  ritual: "A repeated action or series of actions with personal or cultural meaning.",
  routine: "A regular way of doing things, often in a set order.",
  attention: "The act of concentrating the mind on a person, task, or thing.",
  distraction: "Something that draws attention away from what someone is doing.",
  energy: "The capacity to do work or the strength and vitality needed for activity.",
  timeboxing: "Setting a fixed amount of time to work on a specific task.",
  calendar: "A system or schedule that organizes days, dates, and planned events.",
  deadline: "The latest time or date by which something must be completed.",
  workflow: "The sequence of steps used to complete a task or process.",
  systems: "Organized sets of connected parts or rules that work together.",
  progress: "Movement toward a desired goal or a more advanced state.",
  clarity: "The quality of being clear, easy to understand, or well defined.",
  friction: "Resistance or difficulty that slows an action or process.",
  checklist: "A list of items or tasks used to track what needs to be done.",
  constraint: "A limit or restriction that shapes what can be done.",
  simplicity: "The quality of being easy to understand or not overly complicated.",
  rest: "A period of relaxation or inactivity that allows recovery.",
  reflection: "Careful thought about an experience, idea, or action.",
  revolution: "A major and often rapid change in a system or government.",
  empire: "A group of territories or peoples ruled by one authority.",
  migration: "The movement of people or animals from one place to another.",
  dynasty: "A succession of rulers from the same family or line.",
  republic: "A state whose government is carried out by elected representatives.",
  colonization: "The establishment of control over a territory and its people by an outside power.",
  industrialization: "The development of large-scale industry and machine-based production.",
  renaissance: "A revival of art, learning, and culture, especially in Europe from the 14th to 17th centuries.",
  civilization: "A complex society with developed institutions, culture, and technology.",
  archaeology: "The study of past human life through material remains.",
  artifact: "An object made or used by people, especially one of historical interest.",
  archive: "A collection of historical records or the place where they are kept.",
  treaty: "A formal agreement between countries or other groups.",
  monarchy: "A system of government headed by a king, queen, or other monarch.",
  democracy: "A system of government in which people have a role in choosing leaders or laws.",
  trade: "The exchange or sale of goods and services.",
  plague: "A widespread and often deadly infectious disease or epidemic.",
  invention: "A new device, method, or process created through original thought.",
  reform: "A change made to improve a system, law, or institution.",
  propaganda: "Information designed to influence opinion, often by presenting one-sided claims.",
  diplomacy: "The management of relations and negotiations between countries.",
  independence: "The state of being free from outside control or support.",
  heritage: "Traditions, achievements, and features passed down from earlier generations.",
  culture: "The shared customs, beliefs, arts, and practices of a group.",
  chronology: "The arrangement of events in the order in which they happened.",
  battlefield: "The place where a battle is or was fought.",
  exploration: "The act of traveling through or investigating an unfamiliar place or subject.",
  constitution: "A set of fundamental principles or laws by which a state is governed.",
  legacy: "Something handed down from the past or left for the future.",
  narrative: "A spoken or written account of connected events; a story.",
  metaphor: "A figure of speech that describes one thing as another to suggest a similarity.",
  symbolism: "The use of symbols to represent ideas, qualities, or relationships.",
  character: "A person or figure in a story, or the qualities that distinguish someone.",
  setting: "The time and place in which a story or event occurs.",
  conflict: "A struggle between opposing forces, ideas, or characters.",
  dialogue: "A conversation between people, especially in a story or play.",
  imagery: "Descriptive language that helps readers form sensory pictures or impressions.",
  genre: "A category of art or writing defined by shared style or subject.",
  poetry: "Literary writing that uses rhythm, sound, and concentrated language.",
  prose: "Written or spoken language in its ordinary form, rather than verse.",
  satire: "The use of humor or irony to expose foolishness or criticize wrongdoing.",
  tragedy: "A serious story in which a central character faces suffering or downfall.",
  comedy: "A work intended to amuse, often ending happily.",
  myth: "A traditional story that explains beliefs, origins, or natural events.",
  folklore: "Traditional stories, customs, and beliefs shared within a community.",
  allegory: "A story whose characters and events represent deeper ideas or principles.",
  motif: "A recurring image, idea, or element that contributes to a work’s meaning.",
  voice: "A writer’s or speaker’s distinctive style, tone, or point of view.",
  theme: "A central idea or subject explored in a work of art or writing.",
  memoir: "A nonfiction account of selected experiences from the writer’s life.",
  biography: "An account of a person’s life written by someone else.",
  novel: "A long work of fictional prose narrative.",
  fable: "A short tale, often with animal characters, that teaches a lesson.",
  classic: "A work recognized as having lasting importance or high quality.",
  dystopia: "An imagined society marked by oppressive or deeply undesirable conditions.",
  fantasy: "A genre featuring magical or supernatural elements in an imagined world.",
  realism: "An approach that represents life and events in a plausible, lifelike way.",
  imagination: "The ability to form ideas or images of things not present or real.",
  experimentation: "The act of trying new methods to discover what works.",
  craft: "A skill or activity involving making things by hand or with care.",
  design: "The plan or process of creating how something looks, works, or is organized.",
  composition: "The arrangement of elements into a complete work or whole.",
  improvisation: "Creating or performing something spontaneously without full preparation.",
  inspiration: "A feeling or idea that motivates someone to create or act.",
  originality: "The quality of being new, distinctive, or independently created.",
  expression: "The communication of thoughts or feelings through words, art, or action.",
  color: "The visual quality of an object determined by the light it reflects.",
  texture: "The surface quality or feel of a material, or its visual appearance.",
  rhythm: "A pattern of repeated sounds, movements, or events over time.",
  shape: "The outline or form of an object or figure.",
  typography: "The design and arrangement of letters and text.",
  mood: "A temporary emotional state or the feeling created by a work of art.",
  collaboration: "The act of working with others to achieve or create something.",
  play: "An activity done for enjoyment, exploration, or recreation.",
  sketch: "A quick, simple drawing or an early rough plan.",
  remix: "A changed version of an existing song, work, or idea.",
  collage: "An artwork made by combining different materials or images.",
  melody: "A sequence of musical notes perceived as a tune.",
  choreography: "The design and arrangement of movements in a dance or performance.",
  vision: "The ability to see, or a clear idea of a desired future.",
  possibility: "A thing that may happen or be true; potential.",
  commute: "A regular journey between home and work or school.",
  neighbor: "A person who lives near or next to another person.",
  weekend: "The days, usually Saturday and Sunday, outside the standard workweek.",
  household: "The people who live together in one home, or the home itself.",
  grocery: "Food and household items sold by a grocer or bought for a home.",
  conversation: "An informal exchange of ideas or information between people.",
  habit: "A regular behavior repeated often, sometimes without conscious thought.",
  laughter: "The sound or action of laughing in response to amusement or emotion.",
  cooking: "The preparation of food by applying heat or other methods.",
  gardening: "The activity of growing and caring for plants.",
  repair: "The act of fixing something that is damaged or not working.",
  morning: "The early part of the day, from sunrise to noon.",
  generosity: "A willingness to give help, time, or resources to others.",
  nostalgia: "A sentimental longing for a past time or experience.",
  pet: "A domesticated animal kept for companionship or enjoyment.",
  weather: "The state of the atmosphere at a particular place and time.",
  memory: "The ability to store and recall information or an experience remembered.",
  hospitality: "The friendly and generous reception of guests or visitors.",
  surprise: "An unexpected event or the feeling caused by something unforeseen.",
  purpose: "The reason something exists or the intention behind an action.",
  consciousness: "The state of being aware of oneself and one’s surroundings.",
  mortality: "The condition of being subject to death.",
  justice: "The quality of being fair and upholding people’s rights.",
  truth: "The quality or state of being in accordance with fact or reality.",
  meaning: "The idea or significance conveyed by a word, action, or event.",
  reality: "The state of things as they actually exist.",
  morality: "Principles concerning what is right and wrong behavior.",
  existence: "The state of being real or present.",
  destiny: "A future believed to be determined by fate or circumstances.",
  beauty: "The quality of giving pleasure to the senses or mind.",
  happiness: "A state of well-being and contentment.",
  knowledge: "Information and understanding gained through learning or experience.",
  wisdom: "The ability to use knowledge and judgment with good sense.",
  equality: "The state of having the same rights, status, or opportunities.",
  nature: "The physical world and living things not made by people.",
  technology: "The use of scientific knowledge to create tools, systems, or methods.",
  spirituality: "A search for meaning or connection beyond material concerns.",
  time: "The measurable duration in which events happen, from past through present to future.",
  infinity: "A quantity or extent that has no limit or end.",
  choice: "An act of selecting between two or more possibilities.",
  compassion: "Concern for another’s suffering together with a desire to help.",
  society: "A community of people living under shared institutions or relationships.",
  humanity: "People collectively, or the quality of being compassionate and humane.",
  creator: "A person who makes or produces original work or content.",
  audience: "The people who watch, listen to, or read a work or performance.",
  authenticity: "The quality of being genuine and true to one’s character or origins.",
  niche: "A specialized area of interest, activity, or market.",
  sponsorship: "Financial or material support provided in exchange for association or promotion.",
  newsletter: "A regularly distributed publication containing news or information for subscribers.",
  podcast: "A digital audio program released in episodes for listeners.",
  livestream: "A real-time audio or video broadcast over the internet.",
  shortform: "Brief digital content designed to be watched or read quickly.",
  engagement: "The level of attention, interaction, or involvement an audience gives.",
  membership: "The state of belonging to a group, or the status granted to its members.",
  subscription: "A recurring payment that provides continuing access to a service or publication.",
  affiliate: "A person or organization connected with another, often through promotion for commission.",
  brand: "A recognizable identity associated with a product, service, or organization.",
  analytics: "The systematic analysis of data to find patterns and support decisions.",
  ugc: "Content created and shared by users rather than by a brand.",
  discoverability: "How easily a product, service, or piece of content can be found.",
  climate: "The long-term pattern of weather conditions in a region or across Earth.",
  carbon: "A chemical element found in all known living things and many materials.",
  emissions: "Gases or particles released into the air by a process or source.",
  renewable: "Naturally replenished on a human timescale and usable again.",
  solar: "Relating to or powered by energy from the sun.",
  wind: "Moving air, or energy generated by its movement.",
  geothermal: "Relating to heat from within the Earth.",
  battery: "A device that stores chemical energy and supplies electrical power.",
  grid: "An interconnected system that distributes electricity from producers to users.",
  storage: "The act or capacity of keeping something for future use.",
  electrification: "The process of powering equipment or transport with electricity.",
  efficiency: "The ability to achieve a result with little wasted time, energy, or resources.",
  adaptation: "A change that helps an organism or system suit new conditions.",
  biodiversity: "The variety of living organisms in an area or across Earth.",
  ecosystem: "A community of organisms interacting with one another and their environment.",
  conservation: "The protection and careful management of nature or resources.",
  restoration: "The act of returning something to a previous or improved condition.",
  circularity: "An approach that keeps materials in use and reduces waste.",
  recycling: "The process of converting used materials into something usable again.",
  rewilding: "Restoring natural processes and habitats, often by allowing ecosystems to recover.",
  drought: "A prolonged period of unusually low rainfall and water shortage.",
  wildfire: "An uncontrolled fire that spreads through natural vegetation.",
  heatwave: "A prolonged period of unusually hot weather.",
  ocean: "A vast body of salt water covering much of Earth’s surface.",
  methane: "A colorless, odorless gas and potent greenhouse gas with formula CH₄.",
  policy: "A course of action or set of principles adopted by an organization or government.",
  transition: "The process or period of changing from one state or system to another.",
  decarbonization: "The reduction or removal of carbon dioxide emissions from an activity or economy.",
  gameplay: "The rules, actions, and player experience that make up a video game.",
  teamwork: "Cooperative effort by people working together toward a shared goal.",
  campaign: "A planned series of actions or missions directed toward a specific goal.",
  multiplayer: "A game mode in which multiple players participate together.",
  esports: "Organized competitive video gaming, often played before an audience.",
  speedrun: "A playthrough of a game completed as quickly as possible.",
  sandbox: "A game environment that allows players broad freedom to explore or create.",
  quest: "A mission or journey undertaken to achieve a particular goal.",
  avatar: "A digital character or image that represents a person online or in a game.",
  immersion: "A state of deep involvement in an activity or imagined environment.",
  lore: "The background stories and shared knowledge of a fictional world or community.",
  modding: "The practice of modifying a video game or software, often by its users.",
  streaming: "Playing audio or video continuously as it is delivered over a network.",
  console: "An electronic device designed primarily for playing video games.",
  handheld: "Small and portable enough to be held and used in the hands.",
  indie: "Produced independently, especially outside a large commercial studio or publisher.",
  puzzle: "A problem or game that tests ingenuity and requires a solution.",
  simulation: "A representation that imitates the behavior of a real or imagined system.",
  competition: "An event or situation in which people strive to outperform one another.",
  openworld: "A game design that lets players explore a large, freely navigable world.",
  feedback: "Information or reactions used to evaluate or improve an action or product.",
  mindfulness: "Paying deliberate attention to the present moment without judgment.",
  breathwork: "Intentional breathing exercises used to influence physical or mental state.",
  meditation: "A practice of focused attention or awareness to calm and train the mind.",
  boundaries: "Limits that define acceptable behavior or protect personal needs and space.",
  stress: "A state of mental or physical strain caused by demanding circumstances.",
  selfcare: "Actions taken to maintain or improve one’s own health and well-being.",
  sunlight: "Light and energy that come directly from the sun.",
  outdoors: "The open air or natural environment outside buildings.",
  emotional: "Relating to feelings or the expression of feelings.",
  nervoussystem: "The brain, spinal cord, and nerves that coordinate the body’s activity.",
  companionship: "The friendly presence and support of another person or animal.",
  loneliness: "The distressing feeling of lacking meaningful connection with others.",
  connection: "A relationship, link, or sense of closeness between people or things.",
  calm: "A peaceful state with little agitation, worry, or disturbance.",
  vitality: "The state of being strong, active, and full of energy.",
  longevity: "A long duration of life or continued existence.",
  wellbeing: "A person’s overall state of health, comfort, and happiness.",
  fandom: "A community of people who share enthusiasm for a person or work.",
  meme: "An idea, image, or joke that spreads widely, especially online.",
  viral: "Spreading rapidly among people, especially through online sharing.",
  celebrity: "A person widely known by the public, especially in entertainment or sport.",
  soundtrack: "The recorded music and audio accompanying a film, show, or game.",
  premiere: "The first public performance or showing of a work.",
  sequel: "A work that continues the story or events of an earlier one.",
  franchise: "A series of related works or businesses operating under one established name.",
  cosplay: "Dressing as and often performing a character from fiction or popular culture.",
  aesthetic: "A set of visual or artistic qualities that create a distinctive style.",
  crossover: "A work or event combining characters, stories, or styles from different sources.",
  subculture: "A group within a larger culture with distinct interests or customs.",
  fashion: "A popular style of clothing, appearance, or behavior at a particular time.",
  music: "The art of arranging sounds in rhythm and harmony.",
  cinema: "The art and industry of making and showing films.",
  spectacle: "An impressive or striking public display or performance.",
  iconic: "Widely recognized and strongly representative of a person, place, or style.",
  stan: "An intensely devoted fan, especially of a celebrity or artist.",
  trend: "A general direction in which something is changing or becoming popular.",
  catchphrase: "A memorable phrase repeatedly associated with a person or character.",
  representation: "The depiction of someone or something, especially in art or media.",
  zeitgeist: "The defining spirit, ideas, and mood of a particular period.",
  throwback: "A reference to or reminder of an earlier time or style.",
  hype: "Intense excitement or publicity surrounding something.",
  brainrot: "Slang for low-quality or obsessively consumed online content and its perceived effects.",
  pov: "A viewpoint or perspective from which an experience is presented.",
  grwm: "A video format showing someone getting ready while they talk to viewers.",
  dupe: "An item that imitates another, often more expensive, product.",
  unboxing: "A video or activity showing a new product being removed from its packaging.",
  doomscrolling: "Compulsively reading a long stream of upsetting online news or posts.",
  reaction: "A response to an event, statement, or piece of content.",
  discourse: "Written or spoken communication, especially discussion of a public issue.",
  virality: "The quality or process of spreading rapidly from person to person online.",
  microtrend: "A short-lived style or behavior that briefly becomes popular in a small group.",
  parasocial: "Describing a one-sided sense of connection with a public figure or media personality.",
  clickbait: "Online content with a sensational title designed to attract clicks.",
  ragebait: "Content deliberately designed to provoke anger and increase engagement.",
  stitch: "A short video that incorporates and responds to another creator’s video.",
  comment: "A spoken or written remark expressing an opinion or observation.",
  subreddit: "A topic-focused community within the Reddit website.",
  emoji: "A small digital image or symbol used to express an idea or emotion.",
  copypasta: "A block of text repeatedly copied and shared online, often as a joke.",
  challenge: "A difficult task or invitation to test one’s abilities.",
  hashtag: "A word or phrase preceded by # that labels and links online content.",
  cosmos: "The universe regarded as an ordered and interconnected whole.",
  galaxy: "A huge system of stars, gas, dust, and dark matter held together by gravity.",
  exoplanet: "A planet that orbits a star outside our solar system.",
  telescope: "An instrument that gathers and magnifies light to observe distant objects.",
  orbit: "The curved path of one object around another due to gravity.",
  asteroid: "A small rocky body that orbits the sun.",
  comet: "An icy body that develops a glowing cloud or tail near the sun.",
  nebula: "A vast cloud of gas and dust in space.",
  gravity: "The force that attracts objects with mass toward one another.",
  relativity: "Einstein’s theories describing how space, time, and gravity relate to motion and mass.",
  molecule: "A group of atoms bonded together as the smallest unit of a substance.",
  genome: "The complete set of genetic information in an organism.",
  evolution: "The change in inherited traits of populations over generations.",
  neuron: "A specialized cell that transmits information through electrical and chemical signals.",
  particle: "A very small piece or unit of matter.",
  fusion: "The joining of atomic nuclei, releasing energy under suitable conditions.",
  fission: "The splitting of an atomic nucleus, often releasing energy.",
  materials: "The substances from which objects or products are made.",
  spectroscopy: "The study of matter through its interaction with different wavelengths of light.",
  darkmatter: "Matter inferred from its gravitational effects that does not emit detectable light.",
  observatory: "A place equipped for observing astronomical or atmospheric phenomena.",
  astronaut: "A person trained to travel and work in space.",
  mission: "A specific task, journey, or operation undertaken to achieve a goal.",
  discovery: "The act of finding or learning something previously unknown.",
  hypothesis: "A proposed explanation that can be tested through investigation.",
  silhouette: "The dark outline or shape of something seen against a lighter background.",
  maximalism: "A style favoring abundance, complexity, and bold combinations of elements.",
  vintage: "Relating to an earlier period and valued for its age or distinctive quality.",
  upcycling: "Reusing discarded materials to create something of greater value or quality.",
  capsule: "A small collection of versatile clothing designed to work well together.",
  streetwear: "Casual fashion influenced by skate, hip-hop, and urban youth culture.",
  couture: "High-quality custom-fitted clothing made to a client’s measurements.",
  palette: "A range of colors chosen for an artwork, design, or collection.",
  draping: "Arranging fabric on a body or form to shape a garment.",
  tailoring: "The craft of making or altering fitted clothing.",
  material: "The substance from which an object or garment is made.",
  accessory: "An item added to clothing or an outfit for use or decoration.",
  personalstyle: "An individual’s characteristic way of choosing and combining clothing or design.",
  statement: "An expression of an idea, or an item intended to attract attention.",
  uniform: "A distinctive set of clothes worn by members of a group.",
  colorway: "A particular combination of colors used in a design or product.",
  pattern: "A repeated decorative design or a regular arrangement of elements.",
  proportion: "The relationship in size or amount between parts of a whole.",
  ornament: "An object or detail added to decorate something.",
  timelessness: "The quality of seeming unaffected by changes in fashion or time.",
  wearable: "Suitable or designed to be worn, especially as clothing or technology.",
  accessibility: "The design of products and spaces so people with different abilities can use them.",
  influence: "The power to affect someone’s actions, opinions, or the development of something.",
  reach: "The number or range of people who can be contacted or influenced.",
  skill: "The ability to do something well, usually gained through practice or training.",
  survival: "The act or state of continuing to live or exist despite danger or hardship.",
  therapy: "Treatment intended to relieve or heal a physical or mental health problem.",
};

const normalizedDefinitions = new Map(
  Object.entries(definitions).map(([word, definition]) => [word.toLowerCase(), definition]),
);

export function getWordDefinition(word: string) {
  return normalizedDefinitions.get(word.trim().toLowerCase()) ?? null;
}

export const missingWordDefinitions = allCategoryPrompts.filter((word) => !getWordDefinition(word));
